#pragma once

#define DEFAULT_DAY_COLOUR (GColorWhite)
#define DEFAULT_NIGHT_COLOUR (GColorBlack)

#define HOURS_PER_DAY (24)
#define HOURS_PER_HALF_DAY (HOURS_PER_DAY / 2)
#define MINUTES_PER_HOUR (60)
#define SECONDS_PER_MINUTE (60)
#define MILLISECONDS_PER_SECOND (1000)

#define TIMEOUT_MS (MILLISECONDS_PER_SECOND / 100)
